### ISSUE TITLE
Can't cut/copy/paste since electron 1.4.5-1

### ISSUE THREAD

**Issue by doraskayo** [tensor5/arch-atom#43]
When `electron 1.4.5-1` is installed, trying to cut, copy or paste in Atom throws an error. It works just fine when downgrading to `electron 1.4.4-1`. Tested in `atom 1.11.2-1` on a Wayland session.

Here's the stack trace:
```
/usr/lib/atom/node_modules/text-buffer/lib/text-buffer.js:871
Error: Cannot read property 'object' of undefined
TypeError: Cannot read property 'object' of undefined
    at ObjectsRegistry.get (/usr/lib/electron/resources/electron.asar/browser/objects-registry.js:44:28)
    at EventEmitter.<anonymous> (/usr/lib/electron/resources/electron.asar/browser/rpc-server.js:315:31)
    at emitMany (events.js:127:13)
    at EventEmitter.emit (events.js:201:7)
    at WebContents.<anonymous> (/usr/lib/electron/resources/electron.asar/browser/api/web-contents.js:219:13)
    at emitTwo (events.js:106:13)
    at WebContents.emit (events.js:191:7)
    at metaToValue (/usr/lib/electron/resources/electron.asar/renderer/api/remote.js:217:13)
    at Clipboard.write (/usr/lib/atom/src/clipboard.js:70:34)
    at Selection.module.exports.Selection.copy (/usr/lib/atom/src/selection.js:748:31)
    at TextEditor.module.exports.TextEditor.copySelectedText (/usr/lib/atom/src/text-editor.js:2876:21)
    at TextEditor.core:copy (/usr/lib/atom/src/register-default-commands.js:429:21)
    at /usr/lib/atom/src/register-default-commands.js:661:34
    at TextBuffer.module.exports.TextBuffer.transact (/usr/lib/atom/node_modules/text-buffer/lib/text-buffer.js:866:18)
    at TextEditor.module.exports.TextEditor.transact (/usr/lib/atom/src/text-editor.js:1519:26)
    at atom-text-editor.newCommandListeners.(anonymous function) (/usr/lib/atom/src/register-default-commands.js:660:22)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/lib/atom/src/command-registry.js:260:29)
    at /usr/lib/atom/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/lib/atom/node_modules/atom-keymap/lib/keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/lib/atom/node_modules/atom-keymap/lib/keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/usr/lib/atom/src/window-event-handler.js:114:36)
    at HTMLDocument.<anonymous> (/usr/lib/atom/src/window-event-handler.js:3:61)
```

**Comment by doraskayo** [comment]
Seems to be fixed in electron 1.4.6-1.
