### ISSUE TITLE
An error when starting Terminal with Atom 1.12.2 and Electron 1.4.6

### ISSUE THREAD

**Issue by fusion809** [tensor5/arch-atom#44]
Hi,

With the following:

**Atom Version**: 1.12.2
**Electron Version**: 1.4.6
**System**: "Arch Linux"
**Thrown From**: Atom Core

when starting terminal-fusion's terminal I get the errors:

### Stack Trace
```bash
Uncaught Error: Cannot read property 'object' of undefined
TypeError: Cannot read property 'object' of undefined
    at ObjectsRegistry.get (/usr/lib/electron/resources/electron.asar/browser/objects-registry.js:44:28)
    at EventEmitter.<anonymous> (/usr/lib/electron/resources/electron.asar/browser/rpc-server.js:334:31)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
    at WebContents.<anonymous> (/usr/lib/electron/resources/electron.asar/browser/api/web-contents.js:228:13)
    at emitTwo (events.js:106:13)
    at WebContents.emit (events.js:191:7)
```

```bash
At /usr/lib/electron/resources/electron.asar/renderer/api/remote.js:217

Error: Cannot read property 'object' of undefined
TypeError: Cannot read property 'object' of undefined
    at ObjectsRegistry.get (/usr/lib/electron/resources/electron.asar/browser/objects-registry.js:44:28)
    at EventEmitter.<anonymous> (/usr/lib/electron/resources/electron.asar/browser/rpc-server.js:334:31)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
    at WebContents.<anonymous> (/usr/lib/electron/resources/electron.asar/browser/api/web-contents.js:228:13)
    at emitTwo (events.js:106:13)
    at WebContents.emit (events.js:191:7)
    at metaToValue (/usr/lib/electron/resources/electron.asar/renderer/api/remote.js:217:13)
    at undefined.descriptor.get [as _events] (/usr/lib/electron/resources/electron.asar/renderer/api/remote.js:129:16)
    at AtomEnvironment.module.exports.AtomEnvironment.storeWindowDimensions (/usr/lib/atom/src/atom-environment.js:674:69)
    at WindowEventHandler.module.exports.WindowEventHandler.handleWindowBlur (/usr/lib/atom/src/window-event-handler.js:190:35)
    at /usr/lib/atom/src/window-event-handler.js:3:59
```

### Config

```json
{
  "core": {
    "customFileTypes": {
      "source.ini": [
        ".buckconfig",
        ".flowconfig"
      ],
      "source.json": [
        ".arcconfig",
        "BUCK.autodeps"
      ],
      "source.octave": [
        ".m"
      ],
      "source.python": [
        "BUCK"
      ],
      "source.shell.install": [
        ".install"
      ]
    },
    "disabledPackages": [
      "language-gfm",
      "language-shellscript",
      "exception-reporting",
      "metrics",
      "project-manager",
      "link"
    ],
    "excludeVcsIgnoredPaths": false,
    "projectHome": "/home/fusion809/GitHub/mine",
    "telemetryConsent": "no",
    "themes": [
      "fusion-ui",
      "dark-bint-syntax"
    ]
  },
  "editor": {
    "fontSize": 13,
    "showIndentGuide": true,
    "softWrap": true
  }
}
```

### Installed Packages

```coffee
# User
ask-stack, v2.2.0 (inactive)
atom-oss-license, v1.0.0 (active)
autocomplete-clang, v0.10.0 (active)
autocomplete-java, v1.2.5 (inactive)
autocomplete-modules, v1.6.7 (active)
autocomplete-python, v1.8.11 (active)
browser-plus, v0.0.83 (active)
dark-bint-syntax, v0.8.9 (active)
file-icons, v1.7.25 (active)
fusion-ui, v0.12.0 (active)
git-plus, v5.25.1 (active)
git-time-machine, v1.5.3 (inactive)
gpp-compiler, v3.0.7 (active)
hyperclick, v0.0.39 (active)
hyperlink-hyperclick, v1.3.3 (active)
language-ada, v1.1.0 (active)
language-archlinux, v0.9.2 (inactive)
language-asciidoc, v1.5.3 (active)
language-d, v3.3.1 (active)
language-debian, v0.2.1 (active)
language-docker, v1.1.7 (active)
language-emacs-lisp, v1.1.1 (active)
language-fsharp, v0.8.4 (active)
language-gfm2, v0.92.2 (active)
language-gnuplot-atom, v0.2.0 (active)
language-haskell, v1.9.12 (active)
language-ini-desktop, v1.18.3 (active)
language-latex, v1.0.0 (active)
language-liquid, v0.5.1 (active)
language-lua, v0.9.11 (active)
language-pascal, v0.18.1 (active)
language-patch2, v1.0.0 (active)
language-rpm-spec, v0.11.0 (active)
language-rust, v0.4.8 (active)
language-scala, v1.1.8 (active)
language-unix-shell, v0.39.0 (active)
language-vala-modern, v0.3.2 (active)
latex-plus, v0.9.1 (inactive)
linter, v1.11.18 (active)
linter-clang, v3.4.4 (active)
linter-coffeescript, v1.0.0 (active)
linter-js-tenx, v4.0.1 (active)
markdown-toc, v0.4.1 (inactive)
markdown-writer, v2.6.2 (inactive)
minimap, v4.25.6 (active)
package-sync, v1.1.0 (active)
pigments, v0.37.0 (active)
script, v3.11.1 (inactive)
terminal-fusion, v2.4.2 (active)
tool-bar, v1.0.1 (active)
toolbar-fusion, v0.8.5 (active)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.45.0 (inactive)
base16-tomorrow-dark-theme, v1.3.0 (inactive)
base16-tomorrow-light-theme, v1.3.0 (inactive)
one-dark-ui, v1.6.2 (inactive)
one-light-ui, v1.6.2 (inactive)
one-dark-syntax, v1.5.0 (inactive)
one-light-syntax, v1.5.0 (inactive)
solarized-dark-syntax, v1.0.5 (inactive)
solarized-light-syntax, v1.0.5 (inactive)
about, v1.7.0 (active)
archive-view, v0.62.0 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.13.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.4 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.42.0 (active)
bracket-matcher, v0.82.2 (active)
command-palette, v0.39.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (inactive)
find-and-replace, v0.202.2 (inactive)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.60.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.2 (inactive)
markdown-preview, v0.158.8 (active)
metrics, v1.1.1 (inactive)
notifications, v0.65.1 (active)
open-on-github, v1.2.1 (inactive)
package-generator, v1.0.1 (inactive)
settings-view, v0.243.1 (active)
snippets, v1.0.4 (active)
spell-check, v0.68.4 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.2 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.103.0 (active)
timecop, v0.33.2 (active)
tree-view, v0.210.0 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.35.0 (active)
wrap-guide, v0.38.2 (active)
language-c, v0.54.0 (active)
language-clojure, v0.22.1 (active)
language-coffee-script, v0.48.0 (active)
language-csharp, v0.12.1 (active)
language-css, v0.40.1 (active)
language-gfm, v0.88.0 (inactive)
language-git, v0.15.0 (active)
language-go, v0.43.0 (active)
language-html, v0.46.1 (active)
language-hyperlink, v0.16.1 (active)
language-java, v0.24.0 (active)
language-javascript, v0.122.0 (active)
language-json, v0.18.3 (active)
language-less, v0.29.6 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.37.0 (active)
language-php, v0.37.3 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.1 (active)
language-ruby, v0.70.2 (active)
language-ruby-on-rails, v0.25.1 (active)
language-sass, v0.57.0 (active)
language-shellscript, v0.23.0 (inactive)
language-source, v0.9.0 (active)
language-sql, v0.25.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.29.1 (active)
language-toml, v0.18.1 (active)
language-xml, v0.34.12 (active)
language-yaml, v0.27.1 (active)

# Dev
No dev packages
```

Thanks for your time,
Brenton

**Comment by tensor5** [comment]
Thanks for reporting, I'll look into it.
