### ISSUE TITLE
Atom can't run

### ISSUE THREAD

**Issue by drxos** [tensor5/arch-atom#51]
I installed atom with `pacman -S atom`. But it failed running with no error. How can I fix this issue ?

**Comment by tensor5** [comment]
What version are you running? (`pacman -Q atom`)

**Comment by pszafer** [comment]
I have same error as @drxos , but I will provide some more info...

~~~
#pacman -Q atom
atom 1.18.0-2
~~~

Run atom from gnome desktop:
~~~
#journalctl -f
bash: cannot set terminal process group (-1): Inappropriate ioctl for device
bash: no job control in this shell
~~~

running directly
~~~
/usr/bin/atom
~~~

giving in journal:
~~~
org.gnome.Shell.desktop[970]: Window manager warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0x4200001 (Atom)
~~~

About:
GNOME Shell 3.24.3

**Comment by ll931217** [comment]
Mine doesn't run either, nothing shows up on my journal or I am not running it properly. I did run atom directly from `/usr/bin/atom` but nothing shows up, no errors.

    > pacman -Q atom
    atom 1.23.3-2

**Comment by tensor5** [comment]
@ll931217, can you run `electron /usr/lib/atom` and report me what is the output?

**Comment by tensor5** [comment]
What `electron` package are you using?

**Comment by ll931217** [comment]
The global one which is the same version as my local one which is `v1.8.2`

**Comment by tensor5** [comment]
Wait... I said `electron /usr/lib/atom`, not `electron /usr/bin/atom`

**Comment by tensor5** [comment]
And you should use electron downloaded with pacman: `pacman -S electron`

**Comment by ll931217** [comment]
Oh, oops haha sorry.

```shell
❯ electron /usr/lib/atom
App threw an error during load
Error: The module '/usr/lib/atom/node_modules/nslog/build/Release/nslog.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 54. This version of Node.js requires
NODE_MODULE_VERSION 57. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:172:20)
    at Object.Module._extensions..node (module.js:598:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:172:20)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/lib/atom/node_modules/nslog/lib/nslog.js:5:11)
    at Object.<anonymous> (/usr/lib/atom/node_modules/nslog/lib/nslog.js:15:4)
A JavaScript error occurred in the main process
Uncaught Exception:
Error: The module '/usr/lib/atom/node_modules/nslog/build/Release/nslog.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 54. This version of Node.js requires
NODE_MODULE_VERSION 57. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:172:20)
    at Object.Module._extensions..node (module.js:598:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:172:20)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/lib/atom/node_modules/nslog/lib/nslog.js:5:11)

```

**Comment by tensor5** [comment]
Exactly!  You are using the wrong electron version. Download it with pacman.

**Comment by ll931217** [comment]
Thank you @tensor5, that fixed it.
