### ISSUE TITLE
Atom Node 6 Incompatibility

### ISSUE THREAD

**Issue by willotter** [tensor5/arch-atom#9]
I have just update nodejs in Arch to v6.0.0. I don't think Atom is compatible with this version as I think it uses an old version of graceful-fs.

The bugs I am getting currently mean I can't install new packages. Here is the output I get from the featured packages page.
``` 
Fetching featured packages failed.Hide output…
(node:13962) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.

(node:13962) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.

module.js:568
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: Module version mismatch. Expected 48, got 47.
    at Error (native)
    at Object.Module._extensions..node (module.js:568:18)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/lib/node_modules/atom-package-manager/node_modules/git-utils/lib/git.js:8:16)
    at Object.<anonymous> (/usr/lib/node_modules/atom-package-manager/node_modules/git-utils/lib/git.js:371:4)
    at Module._compile (module.js:541:32)
```

**Comment by willotter** [comment]
Hi,
Sorry didn't see you had already pushed an update to fix this. Thanks very much for being so speedy :+1:
